# HTTP Server
server:
  tomcat:
    max-threads: 1
  port: 15681  # HTTP (Tomcat) port

spring:
  application:
    name: ts-ticketinfo-service
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0